### ISSUE TITLE
factory method for making ACEtk::Table

### ISSUE THREAD

**Issue by david8dixon** [njoy/ACEtk#1]
Would be nice to hide to following in the body of a factory method:
      auto contents = njoy::utility::slurpFileToMemory( filename );
      njoy::ACEtk::State< std::string::iterator > s{ 1, contents.begin(), contents.end() };  
      auto table = Table( s );

e.g.
  auto table = njoy::ACEtk::make< Table >( aceFileContaingTable );

**Comment by apmccartney** [comment]
Added a few ctors to the table.

```cpp
njoy::ACEtk::Table table( Istream& );
njoy::ACEtk::Table table( Istream&& );
njoy::ACEtk::Table table( Range& );
njoy::ACEtk::Table table( Range&& );
```

so you can do something like 

```cpp
njoy::ACEtk::Table table1( njoy::utility::slurpFileToMemory("path/to/file") );
njoy::ACEtk::Table table2( std::ifstream("path/to/file") );
```

(the former is about a factor of 3 times faster than the latter in my testing. See `Table.test.cpp` for more)
