### ISSUE TITLE
Unable to read MCNP6 xsdir files: Expected 'datapath'

### ISSUE THREAD

**Issue by lively-michael** [njoy/ACEtk#124]
When attempting to read a valid MCNP6 xsdir file with `ACEtk.Xsdir.from_file(...)`, ACEtk errors out with the error text:

    [error] Expected 'datapath' but found '#-------'

No xsdir files distributed with MCNP6.2 or 6.3 contain the expected 'datapath' string, at least not in my data directories. ACEtk should probably not error out in these cases, but set an appropriate default value based on the data directory structure of MCNP (probably `datapath = ".";` I guess?).

----

EDIT: Attempting to modify an MCNP6 xsdir file to be compatible with what ACEtk expects reveals some additional problems:

* ACEtk is not able to handle the comment character `#`, and any comment line will cause an error: `Something went wrong while reading an xsdir entry`
* ACEtk is not able to handle end-of-file and throws the error `Expected an additional line but found the end of stream`. This occurs even if there is no blank line at the end of the xsdir file; with two or more blank lines at the end the error reverts to `Something went wrong...`. ~~My suggestion here would be to process the input file stream one line at a time (by using `std::getline` and feeding the result into a ``std::stringstream` after validating; this seems convoluted but is more reliable) instead of trying to read XsdirEntry objects directly from the file stream. This allows trimming and checking for empty lines/EOF before attempting to build a XsdirEntry.~~ *Doesn't work with the program flow.*

**Comment by whaeck** [comment]
Thanks for the heads up. You are correct: it does not take into account the # character for comment lines. I'll see about adding that as soon as possible. The current coding does allow for an xsdir without the presence of the datapath line (it is an optional). The unit test for the Xsdir class tests this particular feature.

The end of stream issue is probably inside the XsdirEntry itself. I might not properly test things while reading the xsdir entries.

**Comment by whaeck** [comment]
Fun fact: the MCNP 6.3 manual description of the xsdir file (appendix B) does not mention the use of the # character as a comment character. It seems to be an undocumented feature.

**Comment by whaeck** [comment]
Issue resolved in #125
