### ISSUE TITLE
table.data.print()

### ISSUE THREAD

**Issue by david8dixon** [njoy/ACEtk#2]
Given a working Table, the following will not compile:
```
std::ostringstream oss;  
Table.print( oss ); 
```

I only saw testing for ``` table.header.print() ```and it appears to work, but I am not certain that I am using ``` table.print() ``` correctly. I discovered this when working on feature/el03-temporary. Test will be pushed up shortly

**Comment by apmccartney** [comment]
fix'd on `feature/el03-temporary`!
