### ISSUE TITLE
ACEtk input examples 

### ISSUE THREAD

**Issue by Ebiwonjumi** [njoy/ACEtk#79]
I am trying to use ACEtk to perturb some ace files but can't seem to find input examples. The one here (https://mcnpx.lanl.gov/pdf_files/TechReport_2022_LANL_LA-UR-22-30716_KleedtkeHaeckEtAl.pdf) didn't work after some modifications.

Here is my input so far, please take a  look.

import sys
sys.path.append(r"/mnt/c/Users/bamidele/Downloads/ACEtk/build")
import ACEtk

table = ACEtk.ContinuousEnergyTable.from_file( '/mnt/c/Users/bamidele/Downloads/endf_b80_ace/4009.800nc' )

mt_rxn_index = table.MTR.reaction_numbers.to_list()

mt_number = 16
index = table.MTR.index(mt_number)
mt_xs_data = table.SIG.cross_section_data(index)
mt_xs_data_values = mt_xs_data.cross_sections.to_list()
energy_grid = table.ESZ.energies.to_list()

disap_xs_data_values = table.ESZ.disappearance.to_list()
total_xs_data_values = table.ESZ.total.to_list()
perturbed_energy_indices = list(range(1,len(energy_grid)))

perturbation_fraction = 0.2

# manual perturbation of ACE file, perturb xs values by some amount 
for k in perturbed_energy_indices:
    a = mt_xs_data_values[k]
    b = mt_xs_data_values[k] * perturbation_fraction
    difference = b - a
    mt_xs_data_values[k] = b 
    disap_xs_data_values[k + mt_xs_data.energy_index] = disap_xs_data_values[k + mt_xs_data.energy_index] + difference
    total_xs_data_values[k + mt_xs_data.energy_index] = total_xs_data_values[k + mt_xs_data.energy_index] + difference
        
 # create new SIG block end ESZ block with perturbed values
    new_xs_data = ACEtk.CrossSectionData( mt_xs_data.energy_index, mt_xs_data_values )
    old_SIG = [ table.SIG.cross_section_data(i) for i in range( 1, table.NTR + 1 ) ]
    old_SIG[table.MTR.index( mt_number ) - 1] = new_xs_data
    new_SIG = ACEtk.CrossSectionBlock( old_SIG )
    new_ESZ = ACEtk.PrincipalCrossSectionBlock( energies = table.ESZ.energies.to_list(), total = total_xs_data_values, disappearance = disap_xs_data_values, elastic = table.ESZ.elastic.to_list(), heating = table.ESZ.heating.to_list() )
     
 # save perturbed ACE info to new ace file
    new_Table = ACEtk.ContinuousEnergyTable( z = table.Z, a = table.A, header = table.header, esz = new_ESZ, nu = table.Nu, dnu = table.DNU, mtr = table.MTR, lqr = table.LQR, sig = new_SIG, ang = table.AND, dlw = table.DLW, bdd = tableBDD, dned = table.DNED )
    new_Table.to_file( "4009_plus.ace" )

**Comment by nak4git** [comment]
MT 16 (n,2n) will not have the same energy grid as elastic scattering (ESZ energy grid information)

You can modify your code with the following lines to index the proper energy grid:
energy_index = mt_xs_data.energy_index - 1   # 0-based for Python 
energy_grid = table.ESZ.energies.to_list()
energy_grid = energy_grid[energy_index:-1]   # considering inelastic rxns where energy_index != 1
