### ISSUE TITLE
16 isotopes in Lib80x give error when trying to load ContinuousEnergyTable

### ISSUE THREAD

**Issue by ljacobson64** [njoy/ACEtk#93]
The following 16 isotopes in Lib80x (.00c) give the error "DLW multi-law - currently not implemented" when trying to load them with `ACEtk.ContinuousEnergyTable.from_file()`:

```
B/5010.800nc
O/8017.800nc
F/9019.800nc
Na/11022.800nc
Na/11023.800nc
Ar/18036.800nc
Ar/18038.800nc
Co/1027058.800nc
Ba/56140.800nc
Ta/73182.800nc
Ra/88223.800nc
Ra/88224.800nc
Ra/88225.800nc
Ra/88226.800nc
Am/1095244.800nc
Am/95244.800nc
```

The remaining 540 isotopes in Lib80x load just fine.

**Comment by whaeck** [comment]
Hi Lucas,

You are probably using an older version of ACEtk. We have done most of the development for quite a few different ACE table types but they have not yet made it into develop branch (or the main branch). As you can see from the number of pull requests, we have a bit of a backlog but are actively working on that.

I have been doing performance testing using Lib80x and I know that we can handle the multi-distribution option. You should probably move to using the latest branch, which is currently [fix/dependency-pybind11](https://github.com/njoy/ACEtk/tree/fix/dependency-pybind11).

In a couple of months we will probably have caught up on the develop branch and should be ready for a formal release of ACEtk.

If you have any more questions, suggestions or issues, please feel free to contact us.

Best regards,
Wim

**Comment by ljacobson64** [comment]
Thanks for the info. I checked out the latest branch as you recommended and this fixed the problem for 15 of the 16 problem isotopes.

The one holdout is B-10, and its error message has changed to "DLWH law currently not implemented".

**Comment by whaeck** [comment]
Ah yes, ENDF/B-VIII.0 B10. That ACE file has an issue because the evaluation uses ENDF LAW=0 for the secondary alphas from one of the reactions. Older versions of NJOY2016 do not error out when this ENDF LAW is ecountered. MCNP will crash on this if you transport secondary alphas using this file.

We modified NJOY2016 a long time ago to ensure that no ACE files with this LAW will ever be produced again. In order to solve the issue you're seeing you will have to update the actual ACE file, which you can find here under the errata section: https://nucleardata.lanl.gov/ace/lib80x

**Comment by ljacobson64** [comment]
Thanks for the background! I'm pretty sure I ran an MCNP model some years back that worked fine when running in `mode n p` but encountered strange crashes when I turned on charged particle tracking. I'm pretty sure that model had some boron in it, so that's a long-standing mystery solved.

I just replaced my B-10 ACE files with the updated ones and the error went away.

**Comment by whaeck** [comment]
You're welcome. If you have other issues, questions or suggestions, please let us know.

I'm closing this issue since it is fully resolved.
